spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: servicespringcloud-config-smilexl-dev
---
spring:
  profiles: test   #测试环境
  application: 
    name: servicespringcloud-config-smilexl-test
#  请保存为UTF-8格式





